<a href="https://colab.research.google.com/github/WhoisHOO/HOOAI/blob/main/Random_Seed_HOOAI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# New Section

In [34]:
import random

random.seed(10)
print(random.random())


0.5714025946899135


In [41]:
random.seed(5)
print(random.random())

0.6229016948897019


In [40]:
random.seed(10)
print(random.random())

0.5714025946899135


In [35]:
import numpy as np

np.random.seed(10)
np.random.rand(5)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701])

In [36]:
np.random.rand(10)

array([0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981,
       0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096])

In [37]:
np.random.seed(10)

In [38]:
np.random.rand(5)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701])

In [39]:
np.random.rand(10)

array([0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981,
       0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096])